routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\NoteController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/token', function () {
    return csrf_token(); 
})->middleware('auth')->middleware('throttle:10,1'); // Ini membuat token CSRF kadaluarsa setelah 10 request dalam 1 menit

Route::get('/register', 'Auth\RegisterController@showRegistrationForm')->name('register');
Route::post('/register', 'Auth\RegisterController@register');

Route::get('/login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('/login', 'Auth\LoginController@login');

Auth::routes();
Route::get('/dashboard', [DashboardController::class, 'index'])->middleware('auth')->name('dashboard');
Route::resource('notes', NoteController::class);
Route::get('/notes', [NoteController::class, 'index'])->middleware('auth')->name('notes.index');
Route::get('/notes/{id}', [NoteController::class, 'show'])->middleware('auth')->name('notes.show');
Route::post('/notes/create', [NoteController::class, 'create'])->middleware('checkUserRole')->name('notes.create');
Route::put('/notes/{id}', [NoteController::class, 'update'])->middleware('checkUserRole')->name('notes.update');
Route::delete('/notes/{id}', [NoteController::class, 'destroy'])->middleware('checkUserAdmin')->name('notes.destroy');

// Route::group(['middleware' => 'admin'], function () {
//     Route::post('/notes/create', [NoteController::class, 'create'])->name('notes.create');
//     Route::put('/notes/{id}', [NoteController::class, 'update'])->name('notes.update');
//     Route::delete('/notes/{id}', [NoteController::class, 'destroy'])->name('notes.destroy');
//     // Rute-rute yang hanya dapat diakses oleh admin
// });

// Route::group(['middleware' => 'editor'], function () {
//     Route::post('/notes/create', [NoteController::class, 'create'])->name('notes.create');
//     Route::put('/notes/{id}', [NoteController::class, 'update'])->name('notes.update');
//     // Rute-rute yang hanya dapat diakses oleh editor
// });

// Route::group(['middleware' => 'user'], function () {
//     // Rute-rute yang dapat diakses oleh pengguna biasa
// });

// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Note.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Note extends Model
{
    use HasFactory;
    public function user()
    {
        return $this->belongsTo(User::class);
    }

}

app/Http/Controllers/NoteController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Note;

class NoteController extends Controller
{
    public function index()
    {
        $notes = Note::all(); // Ambil semua catatan dari database

        if (request()->wantsJson()) {
            return response()->json($notes);
        }

        return view('notes.index', compact('notes'));
    }

    public function create()
    {
        $this->middleware('checkUserRole');

        // Periksa tipe permintaan, jika permintaan adalah JSON, langsung arahkan ke store
        if (request()->wantsJson()) {
            return $this->store(request());
        }

        return view('notes.create');
    }

    public function store(Request $request)
    {
        // Validasi dan simpan catatan baru
        $validatedData = $request->validate([
            'title' => 'required|string|max:255',
            'content' => 'required|string',
        ]);

        $note = new Note();
        $note->title = $validatedData['title'];
        $note->content = $validatedData['content'];
        $note->user_id = auth()->user()->id; // Asumsi user_id adalah kolom yang menunjukkan pemilik catatan
        $note->save();

        // Data yang disimpan
        $savedNote = [
            'id' => $note->id,
            'title' => $note->title,
            'content' => $note->content,
            'user_id' => $note->user_id,
        ];

        // Jika permintaan ingin respons JSON (misalnya, saat menggunakan API),
        // Anda dapat mengembalikan respons JSON sebagai berikut:
        if ($request->wantsJson()) {
            return response()->json(['message' => 'Catatan berhasil disimpan', 'data' => $savedNote], 201);
        }

        // Jika permintaan tidak menginginkan respons JSON, maka Anda dapat
        // mengarahkan pengguna kembali ke tampilan dengan pesan sukses:
        return redirect()->route('notes.index')->with('success', 'Catatan berhasil disimpan.');
    }

    public function show(Note $note, Request $request)
    {
        if ($request->wantsJson()) {
            return response()->json($note);
        }

        return view('notes.show', compact('note'));
    }

    public function edit(Note $note)
    {
        $this->middleware('checkUserRole');

        // Periksa tipe permintaan, jika permintaan adalah JSON, langsung arahkan ke update
        if (request()->wantsJson()) {
            return $this->update(request());
        } 

        return view('notes.edit', compact('note'));
    }

    public function update(Request $request, Note $note)
    {
        $this->middleware('checkUserRole');
        // Validasi dan update catatan
        // Validasi data yang diterima dari form
        $validatedData = $request->validate([
            'title' => 'required|string|max:255',
            'content' => 'required|string',
        ]);

        // Perbarui catatan berdasarkan data yang valid
        $note->title = $validatedData['title'];
        $note->content = $validatedData['content'];
        $note->save();

        $updatedNote = [
            'id' => $note->id,
            'title' => $note->title,
            'content' => $note->content,
            'user_id' => $note->user_id,
        ];

        if ($request->wantsJson()) {
            return response()->json(['message' => 'Catatan berhasil diperbarui', 'data' => $updatedNote], 200);
        }

        return redirect()->route('notes.index')->with('success', 'Catatan berhasil diperbarui.');
    }

    public function destroy(Note $note, Request $request)
    {
        $this->middleware('checkUserAdmin');
        // Hapus catatan
        $note->delete();

        if ($request->wantsJson()) {
            return response()->json(['message' => 'Catatan berhasil dihapus'], 201);
        }

        return redirect()->route('notes.index')->with('success', 'Catatan berhasil dihapus.');
    }

}

resources/views/notes/create.blade.php
@extends('layouts.app')

@section('content')
@if(auth()->user()->role === 'user')
    <div class="container">
        <div class="row">
            <div class="col-md-2">
                @include('sidebar') <!-- Sertakan sidebar di sini -->
            </div>
            <div class="col-md-10">
                <div class="card">
                    <div class="card-header">
                        Akses Ditolak
                    </div>
                    <div class="card-body">
                        <h5>Maaf, anda tidak memiliki akses di sini.</h5>
                    </div>
                </div>
            </div>
        </div>
    </div>
        <!-- Konten untuk Pengguna Biasa -->
@elseif(auth()->user()->role === 'editor')
<div class="container">
    <div class="row">
        <div class="col-md-2">
            @include('sidebar') <!-- Sertakan sidebar di sini -->
        </div>
        <div class="col-md-10">
            <h1>Create Note</h1>
            <form action="{{ route('notes.store') }}" method="POST">
                @csrf
                <div class="mb-3">
                    <label for="title" class="form-label">Title</label>
                    <input type="text" class="form-control" id="title" name="title" required>
                </div>
                <div class="mb-3">
                    <label for="content" class="form-label">Content</label>
                    <textarea class="form-control" id="content" name="content" rows="4" required></textarea>
                </div>
                <button type="submit" class="btn btn-success">Create</button>
            </form>
        </div>
    </div>
</div>
        <!-- Konten untuk Editor -->
@elseif(auth()->user()->role === 'admin')
<div class="container">
    <div class="row">
        <div class="col-md-2">
            @include('sidebar') <!-- Sertakan sidebar di sini -->
        </div>
        <div class="col-md-10">
            <h1>Create Note</h1>
            <form action="{{ route('notes.store') }}" method="POST">
                @csrf
                <div class="mb-3">
                    <label for="title" class="form-label">Title</label>
                    <input type="text" class="form-control" id="title" name="title" required>
                </div>
                <div class="mb-3">
                    <label for="content" class="form-label">Content</label>
                    <textarea class="form-control" id="content" name="content" rows="4" required></textarea>
                </div>
                <button type="submit" class="btn btn-success">Create</button>
            </form>
        </div>
    </div>
</div>
        <!-- Konten untuk Admin -->
@endif
@endsection

resources/views/notes/edit.blade.php
@extends('layouts.app')

@section('content')
@if(auth()->user()->role === 'user')
    <div class="container">
        <div class="row">
            <div class="col-md-2">
                @include('sidebar') <!-- Sertakan sidebar di sini -->
            </div>
            <div class="col-md-10">
                <div class="card">
                    <div class="card-header">
                        Akses Ditolak
                    </div>
                    <div class="card-body">
                        <h5>Maaf, anda tidak memiliki akses di sini.</h5>
                    </div>
                </div>
            </div>
        </div>
    </div>
        <!-- Konten untuk Pengguna Biasa -->
@elseif(auth()->user()->role === 'editor')
    <div class="container">
        <div class="row">
            <div class="col-md-2">
                @include('sidebar') <!-- Sertakan sidebar di sini -->
            </div>
            <div class="col-md-10">
                <div class="card">
                    <div class="card-header">
                        Edit Note: {{ $note->title }}
                    </div>
                    <div class="card-body">
                        <form action="{{ route('notes.update', $note) }}" method="POST">
                            @csrf
                            @method('PUT')
                            <div class="mb-3">
                                <label for="title" class="form-label">Title</label>
                                <input type="text" class="form-control" id="title" name="title" value="{{ $note->title }}" required>
                            </div>
                            <div class="mb-3">
                                <label for="content" class="form-label">Content</label>
                                <textarea class="form-control" id="content" name="content" rows="4" required>{{ $note->content }}</textarea>
                            </div>
                            <button type="submit" class="btn btn-primary">Update</button>
                        </form>
                    </div>
                </div>
                <a href="{{ route('notes.index') }}" class="btn btn-secondary mt-3">Back</a>
            </div>
        </div>
    </div>
        <!-- Konten untuk Editor -->
@elseif(auth()->user()->role === 'admin')
    <div class="container">
        <div class="row">
            <div class="col-md-2">
                @include('sidebar') <!-- Sertakan sidebar di sini -->
            </div>
            <div class="col-md-10">
                <div class="card">
                    <div class="card-header">
                        Edit Note: {{ $note->title }}
                    </div>
                    <div class="card-body">
                        <form action="{{ route('notes.update', $note->id) }}" method="POST">
                            @csrf
                            @method('PUT')
                            <div class="mb-3">
                                <label for="title" class="form-label">Title</label>
                                <input type="text" class="form-control" id="title" name="title" value="{{ $note->title }}" required>
                            </div>
                            <div class="mb-3">
                                <label for="content" class="form-label">Content</label>
                                <textarea class="form-control" id="content" name="content" rows="4" required>{{ $note->content }}</textarea>
                            </div>
                            <button type="submit" class="btn btn-primary">Update</button>
                        </form>
                    </div>
                </div>
                <a href="{{ route('notes.index') }}" class="btn btn-secondary mt-3">Back</a>
            </div>
        </div>
    </div>
        <!-- Konten untuk Admin -->
@endif
@endsection

resources/views/notes/index.blade.php
@extends('layouts.app')

@section('content')
@if(auth()->user()->role === 'user')
<div class="container">
    <div class="row">
        <div class="col-md-2">
            @include('sidebar') <!-- Sertakan sidebar di sini -->
        </div>
        <div class="col-md-10">
            <div class="d-flex justify-content-between align-items-center">
                <h1>Notes List</h1>
            </div>
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">ID</th>
                        <th scope="col">Title</th>
                        <th scope="col">Content</th>
                        <th scope="col">Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($notes as $note)
                        <tr>
                            <th scope="row">{{ $note->id }}</th>
                            <td>{{ $note->title }}</td>
                            <td>{{ $note->content }}</td>
                            <td>
                                <a href="{{ route('notes.show', $note) }}" class="btn btn-info">Show</a>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>
    <!-- Konten untuk Pengguna Biasa -->
@elseif(auth()->user()->role === 'editor')
<div class="container">
    <div class="row">
        <div class="col-md-2">
            @include('sidebar') <!-- Sertakan sidebar di sini -->
        </div>
        <div class="col-md-10">
            <div class="d-flex justify-content-between align-items-center">
                <h1>Notes List</h1>
                <a href="{{ route('notes.create') }}" class="btn btn-success">Create</a>
            </div>
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">ID</th>
                        <th scope="col">Title</th>
                        <th scope="col">Content</th>
                        <th scope="col">Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($notes as $note)
                        <tr>
                            <th scope="row">{{ $note->id }}</th>
                            <td>{{ $note->title }}</td>
                            <td>{{ $note->content }}</td>
                            <td>
                                <a href="{{ route('notes.show', $note) }}" class="btn btn-info">Show</a>
                                <a href="{{ route('notes.edit', $note) }}" class="btn btn-primary">Edit</a>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>
    <!-- Konten untuk Editor -->
@elseif(auth()->user()->role === 'admin')
<div class="container">
    <div class="row">
        <div class="col-md-2">
            @include('sidebar') <!-- Sertakan sidebar di sini -->
        </div>
        <div class="col-md-10">
            <div class="d-flex justify-content-between align-items-center">
                <h1>Notes List</h1>
                <a href="{{ route('notes.create') }}" class="btn btn-success">Create</a>
            </div>
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">ID</th>
                        <th scope="col">Title</th>
                        <th scope="col">Content</th>
                        <th scope="col">Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($notes as $note)
                        <tr>
                            <th scope="row">{{ $note->id }}</th>
                            <td>{{ $note->title }}</td>
                            <td>{{ $note->content }}</td>
                            <td>
                                <a href="{{ route('notes.show', $note) }}" class="btn btn-info">Show</a>
                                <a href="{{ route('notes.edit', $note) }}" class="btn btn-primary">Edit</a>
                                <form action="{{ route('notes.destroy', $note->id) }}" method="POST" style="display: inline;">
                                    @csrf
                                    @method('DELETE')
                                    <button type="submit" class="btn btn-danger" onclick="return confirm('Apakah Anda yakin ingin menghapus catatan ini?')">Delete</button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>
    <!-- Konten untuk Admin -->
@endif
@endsection

resources/views/notes/show.blade.php
@extends('layouts.app')

@section('content')
@if(auth()->user()->role === 'user')
<div class="container">
    <div class="row">
        <div class="col-md-2">
            @include('sidebar') <!-- Sertakan sidebar di sini -->
        </div>
        <div class="col-md-10">
            <div class="card">
                <div class="card-header">
                    Note: {{ $note->title }}
                </div>
                <div class="card-body">
                    <h5 class="card-title">Title: {{ $note->title }}</h5>
                    <p class="card-text">Content: {{ $note->content }}</p>
                </div>
                </div>
                <a href="{{ route('notes.index') }}" class="btn btn-primary mt-3">Back</a>
            </div>
        </div>
    </div>
</div>
        <!-- Konten untuk Pengguna Biasa -->
@elseif(auth()->user()->role === 'editor')
<div class="container">
    <div class="row">
        <div class="col-md-2">
            @include('sidebar') <!-- Sertakan sidebar di sini -->
        </div>
        <div class="col-md-10">
            <div class="card">
                <div class="card-header">
                    Note: {{ $note->title }}
                </div>
                <div class="card-body">
                    <h5 class="card-title">Title: {{ $note->title }}</h5>
                    <p class="card-text">Content: {{ $note->content }}</p>
                </div>
                </div>
                <a href="{{ route('notes.index') }}" class="btn btn-primary mt-3">Back</a>
            </div>
        </div>
    </div>
</div>
        <!-- Konten untuk Editor -->
@elseif(auth()->user()->role === 'admin')
<div class="container">
    <div class="row">
        <div class="col-md-2">
            @include('sidebar') <!-- Sertakan sidebar di sini -->
        </div>
        <div class="col-md-10">
            <div class="card">
                <div class="card-header">
                    Note: {{ $note->title }}
                </div>
                <div class="card-body">
                    <h5 class="card-title">Title: {{ $note->title }}</h5>
                    <p class="card-text">Content: {{ $note->content }}</p>
                </div>
                </div>
                <a href="{{ route('notes.index') }}" class="btn btn-primary mt-3">Back</a>
            </div>
        </div>
    </div>
</div>
        <!-- Konten untuk Admin -->
@endif
@endsection